ALTER TABLE `_DATABASE_NAME_`.`Qualification` RENAME TO `_DATABASE_NAME_`.`Qualifier`,
 CHANGE COLUMN `qualificationID` `qualifierID` INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT,
 DROP PRIMARY KEY,
 ADD PRIMARY KEY  USING BTREE(`qualifierID`);


DELETE FROM `_DATABASE_NAME_`.`Qualifier`;
ALTER TABLE `_DATABASE_NAME_`.`Qualifier` 
ADD COLUMN `expressionTypeID` INTEGER UNSIGNED NOT NULL AFTER `qualifierID`;


CREATE TABLE IF NOT EXISTS  `_DATABASE_NAME_`.`ExpressionQualifierProfile` (
  `expressionID` INTEGER UNSIGNED NOT NULL,
  `qualifierID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`expressionID`, `qualifierID`)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;



ALTER TABLE `_DATABASE_NAME_`.`Expression` DROP COLUMN `qualificationID`;